services:

  laravel:
    image: bitnami/laravel:latest
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/src:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: passwd
  
  db:
    image: mariadb:latest
    volumes:
      - ${PWD}/data:/var/lib/mysql/laravel
    environment:
      MARIADB_ROOT_PASSWORD: passwd
      MARIADB_DATABASE: laravel

  admin:
    image: adminer
    ports:
      - 9000:8080