services:

  laravel:
    image: bitnami/laravel:latest
    ports:
      - 8000:8000
    user: bitnami
    working_dir: /app
    volumes:
      - ${PWD}/src:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: passwd
    depends_on:
      - db
  
  db:
    image: mariadb:latest
    volumes:
      - ${PWD}/data:/var/lib/mysql/laravel
    environment:
      MARIADB_ROOT_PASSWORD: passwd
      MARIADB_DATABASE: laravel

  admin:
    image: adminer
    ports:
      - 9000:8080
    depends_on:
      - db

  
